# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3c9aa2548e8f44532d0f4c15073573a85349576a16667c026d11afb6210cb7179191112685a8d7d26b184d04dd5ec2eefa8fb1b2fab7f912207690d24541c3a3

test:
  secret_key_base: 448f3494ecf5f47c38f88a93e35f0faa45cf893b09ecc81564e4d922bf78aa5ba5b5a387b9e9b2897799c0e946e6d41f8e59df2f7f8f7c4576fce61ca686062d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
